FMWebApp451/Controllers/myCrystaliftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminCart;
using FM2015.ViewModels;

namespace FM2015.Controllers
{
    public class myCrystaliftController : Controller
    {
        // GET: myCrystalift
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CustomerInfo()
        {
            CustomerViewModel cvm = new CustomerViewModel();
            cvm = (Session["cvm"] == null) ? cvm : (CustomerViewModel)Session["cvm"];
            ViewBag.ErrorMsg = "";
            cvm.Customer.Email = "email";
            cvm.Customer.Phone = "phone number";
            cvm.Customer.FirstName = "first name";
            cvm.Customer.LastName = "last name";
            cvm.ShipAddress.Street = "street";
            cvm.ShipAddress.Street2 = "street2";
            cvm.ShipAddress.City = "city";
            cvm.ShipAddress.Zip = "postal code"; 
            
            return View(cvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerInfo(CustomerViewModel cvm, string hdnShipState)
        {
            if ((string.IsNullOrEmpty(cvm.Customer.Email) || (cvm.Customer.Email == "email")))
            {
                ViewBag.ErrorMsg = "Email address is required";
                return View (cvm);
            }
            if ((string.IsNullOrEmpty(cvm.Customer.Phone) || (cvm.Customer.Email == "phone number")))
            {
                ViewBag.ErrorMsg = "Phone number is required";
                return View(cvm);
            }
            if ((string.IsNullOrEmpty(cvm.Customer.FirstName) || (cvm.Customer.FirstName == "first name")))
            {
                ViewBag.ErrorMsg = "First Name is required";
                return View(cvm);
            }
            if ((string.IsNullOrEmpty(cvm.Customer.LastName) || (cvm.Customer.LastName == "last name")))
            {
                ViewBag.ErrorMsg = "Last Name is required";
                return View(cvm);
            }
            if ((string.IsNullOrEmpty(cvm.ShipAddress.Street) || (cvm.ShipAddress.Street == "street")))
            {
                ViewBag.ErrorMsg = "Street is required";
                return View(cvm);
            }
            if (cvm.ShipAddress.Street2 == "street2")
            {
                cvm.ShipAddress.Street2 = "";
            }
            if ((string.IsNullOrEmpty(cvm.ShipAddress.City) || (cvm.ShipAddress.City == "city")))
            {
                ViewBag.ErrorMsg = "City is required";
                return View(cvm);
            }
            //string billState = Request["txtBillState"];
            //string shipState = Request["hdnShipState"];
            string shipState = hdnShipState;
            if (shipState.ToUpper() == "STATE/PROVINCE")
            {
                shipState = "";
            }
            cvm = FM2015.Helpers.Helpers.UpdateStateCountrySelectLists(cvm, shipState, shipState);

            if ((string.IsNullOrEmpty(cvm.ShipAddress.Zip) || (cvm.ShipAddress.City == "postal code")))
            {
                ViewBag.ErrorMsg = "Postal Code is required";
                return View(cvm);
            }

            string zipErr = FM2015.Helpers.DBUtil.CheckZipCode(cvm.ShipAddress.Country, cvm.ShipAddress.Zip);
            if (!string.IsNullOrEmpty(zipErr))
            {
                ViewBag.ErrorMsg = zipErr;
                return View(cvm);

            }

            Cart cart = new Cart();
            cart.SiteCustomer = cvm.Customer;
            cart.BillAddress = cvm.BillAddress;
            cart.ShipAddress = cvm.ShipAddress;
            Item item = new Item(13, 1); //CL-P90-club-LI --> CL-P90-LI, Crystalift Microdermabrasion Complete System - club
            cart.Items.AddItem(item);
            cart.CalculateTotals();
            Session["setupFee"] = 59.01M; //establish a setup fee for this offer; used in cart.SubscriptionProcessing
            Session["cvm"] = cvm;
            Session["shopCart"] = cart;
            return RedirectToAction("CustomerShipping");
        }

        public ActionResult CustomerShipping()
        {
            CustomerViewModel cvm = (CustomerViewModel)Session["cvm"];
            Cart cart = (Cart)Session["shopCart"];
            ViewBag.ShippingMethod = "Standard Ground";
            ViewBag.TotalShipping = cart.TotalShipping.ToString("C");
            ViewBag.TotalTax = cart.TotalTax.ToString("C");
            ViewBag.Total = cart.Total.ToString("C");
            return View(cvm);
        }

        public ActionResult CustomerPayment()
        {
            CustomerViewModel cvm = (CustomerViewModel)Session["cvm"];
            Cart cart = (Cart)Session["shopCart"];
            ViewBag.TotalShipping = cart.TotalShipping.ToString("C");
            ViewBag.TotalTax = cart.TotalTax.ToString("C");
            ViewBag.Total = cart.Total.ToString("C");
            return View(cart.Tran);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerPayment(Transaction tran)
        {
            Cart cart = new Cart();
            cart = (Cart)Session["shopCart"];
            cart.Tran = tran;
            Session["shopCart"] = cart;
            ViewBag.TotalShipping = cart.TotalShipping.ToString("C");
            ViewBag.TotalTax = cart.TotalTax.ToString("C");
            ViewBag.Total = cart.Total.ToString("C");

            if (string.IsNullOrEmpty(tran.CardNo))
            {
                ViewBag.ErrorMsg = "Card Number is required";
                return View(tran);
            }
            if (tran.CardNo.Length < 15)
            {
                ViewBag.ErrorMsg = "Card is less than 15 characters.  Please correct, then try again.";
                return View(tran);
            }
            if (string.IsNullOrEmpty(tran.CardHolder))
            {
                ViewBag.ErrorMsg = "Name is required";
                return View(tran);
            }
            if (string.IsNullOrEmpty(tran.ExpDate))
            {
                ViewBag.ErrorMsg = "Expiration is required";
                return View(tran);
            }
            int temp = 0;
            if (!Int32.TryParse(tran.ExpDate.Replace("/",""), out temp))
            {
                ViewBag.ErrorMsg = "Expiration date must be in the form of MM/YY (for instance, 06/15)";
                return View(tran);
            }
            if (string.IsNullOrEmpty(tran.CvsCode))
            {
                ViewBag.ErrorMsg = "CVS is required";
                return View(tran);
            }
            temp = 0;
            if (!Int32.TryParse(tran.CvsCode, out temp))
            {
                ViewBag.ErrorMsg = "CVS must be all numbers";
                return View(tran);
            }

            tran.CardNo = tran.CardNo.Replace(" ", ""); //get rid of any spaces customer may have used
            tran.ExpDate = tran.ExpDate.Replace("/", ""); //get rid of possible / in MM/YY 
            cart.Tran = tran;

            CustomerViewModel cvm = new CustomerViewModel();
            cvm = (CustomerViewModel)Session["cvm"];
            if (cvm.BillAddress.AddressId == 0)
            {
                cvm.BillAddress = cvm.ShipAddress; //if no billing address then use the shipping address as default
            }
            cart.Tran.Address = cvm.BillAddress;
            Session["shopCart"] = cart;

            string promoCodeID = "";
            if (cart.SubscriptionProcessing(promoCodeID) != 0) //transaction was OK if result == 0
            {
                string errMsg = (Session["subErrorMessage"] == null) ? "" : Session["subErrorMessage"].ToString();
                int first = errMsg.IndexOf("errMessage:");
                int last = errMsg.Length;
                int subStringLength = last - first;
                if (first > 0)
                {
                    errMsg = errMsg.Substring(first, subStringLength);
                }
                errMsg = errMsg.Replace("errMessage:", "");
                ViewBag.ErrorMsg = "Your Order did not Successfully complete: " + errMsg;
                return View(tran);
            }
            return RedirectToAction("CustomerThankYou");
        }

        public ActionResult CustomerThankYou()
        {
            System.Threading.Thread.Sleep(1100);
            List<int> list = ShopifyAgent.ShopifyAgent.SyncShopify(); //sync orders from Shopify

            CustomerViewModel cvm = (CustomerViewModel)Session["cvm"];
            Cart cart = (Cart)Session["shopCart"];

            ViewBag.ShippingMethod = "Standard Ground";
            ViewBag.TotalShipping = cart.TotalShipping.ToString("C");
            ViewBag.TotalTax = cart.TotalTax.ToString("C");
            ViewBag.Total = cart.Total.ToString("C");
            ViewBag.Date = DateTime.Now.ToString();
            ViewBag.Name = cvm.Customer.FirstName + " " + cvm.Customer.LastName;
            ViewBag.Street = cvm.ShipAddress.Street;
            ViewBag.City = cvm.ShipAddress.City;
            ViewBag.State = cvm.ShipAddress.State;
            ViewBag.Zip = cvm.ShipAddress.Zip;
            ViewBag.Country = cvm.ShipAddress.Country;
            ViewBag.Email = cvm.Customer.Email;
            return View();
        }

    }
}

FMWebApp451/Views/myCrystalift/CustomerInfo-ORIG.cshtml
@{
    Layout = null;
}

@model FM2015.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "myCrystalift Customer Info";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        <a href="http://www.mycrustalift.com">
            <img src="~/images/Products/crystalift/logo.png" alt="Crystalift Microdermabrasion System" width="20%" />
        </a>
        <p>
        <a href="index" >cart</a>&nbsp;>&nbsp;<strong>Customer Information</strong>&nbsp;>&nbsp;Shipping method&nbsp;>&nbsp;Payment method
        </p>  
              
        <div class="row">
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                @using (Html.BeginForm("CustomerInfo", "myCrystalift", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("hdnShipState", null, new { @id = "hdnShipState", @name = "hdnShipState", @Value = "hdnTest" })
                    @Html.Hidden("hdnBillState", null, new { @id = "hdnBillState" })
                    <span style="color:red">@ViewBag.ErrorMsg</span>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <h3>Customer information</h3>
        <div class="form-group">
            @Html.LabelFor(model => model.Customer.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3>Shipping address</h3>
        <div class="form-group">
            @Html.LabelFor(model => model.Customer.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Customer.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Customer.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.Street2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress.Street2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress.Street2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(m => m.SelectShipCountryCode, new SelectList(Model.ShipCountrySelectList,
                 "Value", "Text", "US"), "Please select a country", new { @id = "ddlShipCountry", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipAddress.Country, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress.State, new { htmlAttributes = new { @ID = "txtShipState", @Name = "txtState", @class = "form-control", @style = "display:none" } })
                @Html.DropDownListFor(m => m.SelectShipStateCode, new SelectList(Model.ShipStateSelectList,
                    "Value", "Text", "CA"), "", new { @id = "ddlShipState", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipAddress.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer.Phone, "", new { @class = "text-danger" })
            </div>
        </div>



        <hr />
        <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                <a href="http://www.mycrystalift.com/collections/all">&lt;&nbsp;Continue Shopping</a>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                <input type="submit" value="Continue To Shipping Method" class="btn btn-primary" onclick='SetStateVals();' />
            </div>
        </div>
    </div>
                }
            </div>

            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5" style="background-color:#FBFBFB; border-left:1px solid silver; height:800px">
                <table width="100%">
                    <tr>
                        <td>
                            <img src="~/images/Products/crystalift/crystalift-160.png" width="50%" alt="Crystalift Microdermabrasion System" />
                        </td>
                        <td style="text-align:left">
                            Crystalift Microdermabrasion<br />
                            Complete System + club membership
                        </td>
                        <td style="text-align:right">
                            $99.00
                        </td>
                    </tr>
                </table>

                <hr />
                <table width="100%">
                    <tr>
                        <td style="text-align:left">
                            Subtotal
                        </td>
                        <td style="text-align:right">
                            $99.00
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:left">
                            Shipping
                        </td>
                        <td style="text-align:right">
                            -----
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:left">
                            Taxes
                        </td>
                        <td style="text-align:right">
                            -----
                        </td>
                    </tr>
                </table>
                <hr />
                <table width="100%">
                    <tr>
                        <td style="text-align:left">
                            Total
                        </td>
                        <td style="text-align:right">
                            USD <span style="font-size:x-large; font-weight:100">$99.00</span>
                        </td>
                    </tr>

                </table>

                </div>
            </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @AdminCart.Config.BizName()</p>
        </footer>

        @section Scripts {
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @Scripts.Render("~/bundles/jqueryval")
            @RenderSection("scripts", required: false)
        }

        <script src="@Url.Content("~/Scripts/jquery/jquery-1.8.3.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/_regHelper.js")" type="text/javascript"></script>
    </div>

</body>
</html>

FMWebApp451/Views/myCrystalift/CustomerPayment.cshtml
@{
    Layout = null;
}

@model AdminCart.Transaction

@{
    ViewBag.Title = "myCrystalift Customer Payment";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <a href="http://www.mycrystalift.com">
            <img src="~/images/Products/crystalift/logo.png" alt="Crystalift Microdermabrasion System" width="20%" />
        </a>
        <p>
            cart&nbsp;>&nbsp;Customer Information&nbsp;>&nbsp;<a href="CustomerShipping">Shipping method</a>&nbsp;>&nbsp;<strong>Payment method</strong>
        </p>
        <div class="row">
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <span style="color:red">@ViewBag.ErrorMsg</span>
                    @Html.Partial("_RegisterCPPartial")
                }
            </div>
            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5" style="background-color:#FBFBFB; border-left:1px solid silver; height:800px">
                <table width="100%">
                    <tr>
                        <td>
                            <img src="~/images/Products/crystalift/crystalift-160.png" alt="Crystalift Microdermabrasion System" width="50%" />
                        </td>
                        <td style="text-align:left">
                            Crystalift Microdermabrasion<br />
                            Complete System + club membership
                        </td>
                        <td style="text-align:right">
                            $99.00
                        </td>
                    </tr>
                </table>

                <hr />
                <table width="100%">
                    <tr>
                        <td style="text-align:left">
                            Subtotal
                        </td>
                        <td style="text-align:right">
                            $99.00
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:left">
                            Shipping
                        </td>
                        <td style="text-align:right">
                            @if (ViewBag.TotalShipping == "$0.00")
                            {
                                <span>FREE</span>
                            }
                            else
                            {
                                <span>@ViewBag.TotalShipping</span>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:left">
                            Taxes
                        </td>
                        <td style="text-align:right">
                            <span>@ViewBag.TotalTax</span>
                        </td>
                    </tr>
                </table>
                <hr />
                <table width="100%">
                    <tr>
                        <td style="text-align:left">
                            Total
                        </td>
                        <td style="text-align:right">
                            USD <span style="font-size:x-large; font-weight:100">@ViewBag.Total</span>
                        </td>
                    </tr>

                </table>
            </div>
        </div><!-- end row-->

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @AdminCart.Config.BizName()</p>
            <!-- GeoTrust QuickSSL [tm] Smart  Icon tag. Do not edit. -->
            <script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
            <!-- end  GeoTrust Smart Icon tag -->
        </footer>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("scripts", required: false)
    }

    <script src="@Url.Content("~/Scripts/jquery/jquery-1.8.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>

    <script type="text/javascript">
    //EMAIL
    $(function () { //Document ready shorthand
        orig_val = '';
        cardNum_val = $('#txtCardNum').val(); //Get the original value to test against. We use .val() to grab value="Search"
        cardName_val = $('#txtCardName').val();
        expDate_val = $('#txtExpDate').val();
        cvc_val = $('#txtCVC').val();
        $('input:text').focus(function () { //When the user tabs/clicks the search box.
            orig_val = $(this).val();
            switch ($(this).val()) {
                case cardNum_val:
                case cardName_val:
                case expDate_val:
                case cvc_val:
                    $(this).val('');
                    break;

            }
        })
        .blur(function () {//When the user tabs/clicks out of the input
            if ($(this).val() === '') {//If the value is blank (such as the user clicking in it and clicking out)...
                $(this).val(orig_val); //... set back to the original value
            }
        });
    });
    </script>

</body>
</html>

FMWebApp451/Views/myCrystalift/CustomerShipping.cshtml
@{
    Layout = null;
}

@model FM2015.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "myCrystalift Customer Shipping";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <a href="http://www.mycrystalift.com">
            <img src="~/images/Products/crystalift/logo.png" alt="Crystalift Microdermabrasion System" width="20%" />
        </a>
        <p>
            cart&nbsp;>&nbsp;<a href="CustomerInfo">Customer Information</a>&nbsp;>&nbsp;<strong>Shipping method</strong>&nbsp;>&nbsp;Payment method
        </p>

    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
            <h3>Shipping Address</h3>
            @Html.DisplayFor(model => model.Customer.FirstName)&nbsp;@Html.DisplayFor(model => model.Customer.LastName)<br />
            @Html.DisplayFor(model => model.ShipAddress.Street)<br />
            @if (!string.IsNullOrEmpty(Model.ShipAddress.Street2))
            {
                @Html.DisplayFor(model => model.ShipAddress.Street2)<br />
            }
            @Html.DisplayFor(model => model.ShipAddress.City),&nbsp;
            @Html.DisplayFor(model => model.ShipAddress.State)&nbsp;
            @Html.DisplayFor(model => model.ShipAddress.Zip)<br />
            @Html.DisplayFor(model => model.ShipAddress.Country)<br />

            @Html.DisplayFor(model => model.Customer.Phone)<br />
            <a href="CustomerInfo">Edit Shipping Address</a>
            <hr />
            <h3>Shipping Method</h3>
            <table width="100%">
                <tr>
                    <td style="text-align:left">
                        @ViewBag.ShippingMethod
                    </td>
                    <td style="text-align:right">
                        @if (ViewBag.TotalShipping == "$0.00")
                        {
                            <span>FREE</span>
                        }
                        else
                        {
                            @ViewBag.TotalShipping
                        }
                    </td>
                </tr>
            </table>

            <hr />
            <div class="row">
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                    <a href="/mycrystalift/customerinfo">&lt;&nbsp;Return To customer information</a>
                </div>
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                    <a href="/mycrystalift/customerpayment"><span class="btn btn-primary" style="text-align:right">Continue to payment method</span></a>
                </div>
            </div>

        </div> <!--end column-->
        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5" style="background-color:#FBFBFB; border-left:1px solid silver; height:800px">
            <table width="100%">
                <tr>
                    <td>
                        <img src="~/images/Products/crystalift/crystalift-160.png" width="50%" alt="Crystalift Microdermabrasion System" />
                    </td>
                    <td style="text-align:left">
                        Crystalift Microdermabrasion<br />
                        Complete System + club membership
                    </td>
                    <td style="text-align:right">
                        $99.00
                    </td>
                </tr>
            </table>

            <hr />
            <table width="100%">
                <tr>
                    <td style="text-align:left">
                        Subtotal
                    </td>
                    <td style="text-align:right">
                        $99.00
                    </td>
                </tr>
                <tr>
                    <td style="text-align:left">
                        Shipping
                    </td>
                    <td style="text-align:right">
                        @if (ViewBag.TotalShipping == "$0.00")
                        {
                            <span>FREE</span>
                        }
                        else
                        {
                            <span>@ViewBag.TotalShipping</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td style="text-align:left">
                        Taxes
                    </td>
                    <td style="text-align:right">
                        <span>@ViewBag.TotalTax</span>
                    </td>
                </tr>
            </table>
            <hr />
            <table width="100%">
                <tr>
                    <td style="text-align:left">
                        Total
                    </td>
                    <td style="text-align:right">
                        USD <span style="font-size:x-large; font-weight:100">@ViewBag.Total</span>
                    </td>
                </tr>

            </table>

        </div>
    </div> <!-- end row-->
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - @AdminCart.Config.BizName()</p>
    </footer>

    @section Scripts {
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("scripts", required: false)
    }

    <script src="@Url.Content("~/Scripts/jquery/jquery-1.8.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>

</div>
</body>
</html>

FMWebApp451/Views/myCrystalift/Index_Orig.cshtml
@{
    ViewBag.Title = "MyCrystalift $99 Club Checkout";
}

<img src="@Url.Content("~/images/Products/crystalift/crystalift_cartpage.jpg")" usemap="cartMap" />
<map name="cartMap">
    <area shape="rect" href="" coords="670,270,950,310" alt="checkout"/>
    <area shape="rect" href="" coords="320,350,380,360" alt="remove"/>
</map>