FMWebApp451/Controllers/SubscribersController.cs
using FM2015.Models;
using FMWebApp451.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMWebApp451.Controllers
{
    public class SubscribersController : Controller
    {
        private readonly ISubscriptions subscriptionProvider;

        public SubscribersController(ISubscriptions subscriptionProvider)
        {
            this.subscriptionProvider = subscriptionProvider;
        }

        // GET: Subscribers
        public ActionResult Index(string param)
        {
            List<Subscriptions> subscriptions = new List<Subscriptions>();
            Subscriptions sub = new Subscriptions();

            subscriptions = subscriptionProvider.GetAll();
            subscriptions = subscriptions.OrderByDescending(x => x.OrderID).ToList();

            if (string.IsNullOrEmpty(param))
            {
                ; // list all subscriptions if param is null
            }
            else
            {
                if (Int32.TryParse(param, out int orderId))
                {
                    subscriptions = (from s in subscriptions where s.OrderID == orderId select s).ToList();
                }
                else
                {
                    if (param.Contains("sub_"))
                    {
                        subscriptions = (from s in subscriptions where s.StripeSubID.Contains(param) select s).ToList();
                    }
                    else
                    {
                        if (param.Contains("cus_"))
                            {
                                subscriptions = (from s in subscriptions where s.StripeCusID.Contains(param) select s).ToList();
                            }
                    }
                }
            }
            return View(subscriptions);
        }

        // GET: Subscribers/Details/5
        public ActionResult Details(int id)
        {
            List<Subscriptions> subscriptions = new List<Subscriptions>();
            Subscriptions sub = new Subscriptions();

            subscriptions = subscriptionProvider.GetAll();
            sub = (from s in subscriptions where s.ID == id select s).FirstOrDefault();

            return View(sub);
        }

        // GET: Subscribers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Subscribers/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Subscribers/Edit/5
        public ActionResult Edit(int id)
        {
            List<Subscriptions> subscriptions = new List<Subscriptions>();
            Subscriptions sub = new Subscriptions();

            subscriptions = subscriptionProvider.GetAll();
            sub = (from s in subscriptions where s.ID == id select s).FirstOrDefault();

            return View(sub);
        }

        // POST: Subscribers/Edit/5
        [HttpPost]
        public ActionResult Edit(Subscriptions sub)
        {
            if (ModelState.IsValid)
            {
                subscriptionProvider.Update(sub);
                return RedirectToAction("Index", new {param = sub.OrderID.ToString() });
            }
            return View();
        }

        // GET: Subscribers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Subscribers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FMWebApp451/Views/Subscribers/Details.cshtml
@model FM2015.Models.Subscriptions

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Subscriptions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripeSubID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripeSubID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripeCusID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripeCusID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripePlanID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripePlanID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripeSubDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripeSubDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripeStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripeStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StripePromoCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StripePromoCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FMWebApp451/Views/Subscribers/Edit.cshtml
@model FM2015.Models.Subscriptions

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subscriptions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripeSubID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripeSubID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripeSubID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripeCusID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripeCusID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripeCusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripePlanID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripePlanID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripePlanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripeSubDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripeSubDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripeSubDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripeStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripeStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripeStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StripePromoCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StripePromoCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StripePromoCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FMWebApp451/Views/Subscribers/Index.cshtml
@model IEnumerable<FM2015.Models.Subscriptions>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Get All Subscribers</h2>

@Html.Partial("_AdminNav")

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <h4>Find Subscriber</h4>
        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Index", "Subscribers", FormMethod.Get))
        {
            <div class="form-group col-xs-12 col-sm-6 col-md-3">
                @Html.Label("Subscriber: ", htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.TextBox("param", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <p>&nbsp;</p>
            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    <input type="submit" value="Search" class="btn btn-Success" />
                </div>
            </div>
        }
    </div> <!--end Panel Body-->
</div> <!--end Panel-->

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripeSubID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripeCusID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripePlanID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripeSubDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripeStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StripePromoCode)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripeSubID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripeCusID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripePlanID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripeSubDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripeStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StripePromoCode)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            </td>
        </tr>
    }

</table>